name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: "Environment (dev/uat/prod)"
        type: choice
        options:
          - prod
          - uat
          - dev
        required: true
        default: "dev"
      TEST_TYPE:
        description: "TestType"
        type: choice
        default: 'Smoke'
        options:
          - Smoke
          # - E2E
          # - Regression
          - Extended
          # - Widget
          # - Execute_API_Test
          # - Verify_Response_Code
      ALL_MODULES:
        description: "All Modules"
        type: boolean
        default: false
      SELECTED_MODULES:
        description: "Multiple Modules"
        default: '{"CPORT": "1", "CPAC": "0", "SRC": "0", "CA": "0"}'
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.55.0-noble # latest Playwright docker image
    env:
      # Workflow-level environment variable
      # TEST_ENV: "dev"
      TEST_ENV: ${{ github.event.inputs.ENVIRONMENT }}
      TEST_TYPE: ${{ github.event.inputs.TEST_TYPE }}
      ALL_MODULES: ${{ github.event.inputs.ALL_MODULES }}
      SELECTED_MODULES: ${{ github.event.inputs.SELECTED_MODULES }}
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    # - uses: actions/setup-node@v4
      # with:
        # node-version: lts/*
    - name: Install dependencies
      run: npm ci
    # - name: Install Playwright Chromium Browser
      # run: npx playwright install chromium --with-deps
    - name: Run Playwright tests
      run: |
        echo "TEST_ENV : ${{env.TEST_ENV}}"
        echo "TEST_TYPE : ${{env.TEST_TYPE}}"
        echo "ALL_MODULES : ${{env.ALL_MODULES}}"
        echo "SELECTED_MODULES : ${{env.SELECTED_MODULES}}"
        npm run test
      # run: npx playwright test tests/auth.setup.ts
        # npm run test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 1
